/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anastasiaremezova (https://sketchfab.com/anastasiaremezova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-in-flowers-3472121f05d14723951eb56ab8aee4d1
Title: Cat in flowers
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei';
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {
  const group=useRef();
  const { nodes, materials, animations } = useGLTF('/models/cat_in_flowers.glb')
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  useFrame(() => {
    group.current.position.y = ySpring.get();
  });
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale || 0.3}
      position={props.position || [1.3, -1, 0]}>
      <group scale={0.01}>
        <group position={[-0.002, 0.528, 0.005]} scale={[0.853, 0.825, 0.853]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface240_lambert4_0.geometry}
            material={materials.lambert4}
            scale={[1, 1.067, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface241_lambert7_0.geometry}
            material={materials.lambert7}
            position={[0, -0.029, 0]}
            scale={1.115}
          />
        </group>
        <group position={[-0.061, 0.013, -0.011]} rotation={[0.025, -0.017, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder4_lambert3_0.geometry}
            material={materials.lambert3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder4_lambert8_0.geometry}
            material={materials.lambert8}
          />
        </group>
        <group position={[-0.041, 0.035, -0.117]} rotation={[-0.035, 0.277, 0.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder5_lambert3_0.geometry}
            material={materials.lambert3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder5_lambert8_0.geometry}
            material={materials.lambert8}
          />
        </group>
        <group position={[-2.887, 0, -0.032]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface190_lambert5_0.geometry}
            material={materials.lambert5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface190_lambert6_0.geometry}
            material={materials.lambert6}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface130_lambert3_0.geometry}
          material={materials.lambert3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pDisc1_lambert10_0.geometry}
          material={materials.lambert10}
          position={[0, 0.116, 0]}
          scale={[0.804, 1, 0.804]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface244_lambert3_0.geometry}
          material={materials.lambert3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface245_lambert3_0.geometry}
          material={materials.lambert3}
          position={[0.259, 0.212, 0.296]}
          rotation={[0.047, -0.374, 0.265]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert9_0.geometry}
          material={materials.lambert9}
          position={[-0.035, 0.611, 0.388]}
          rotation={[-2.133, 0, 0]}
          scale={[0.042, 0.031, 0.042]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert9_0.geometry}
          material={materials.lambert9}
          position={[-0.065, 1.734, -0.063]}
          rotation={[-1.306, 0, 0]}
          scale={[0.05, 0.037, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert9_0.geometry}
          material={materials.lambert9}
          position={[-0.254, 1.29, 0.072]}
          rotation={[-1.306, 0, 0.006]}
          scale={[0.037, 0.027, 0.037]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cat_in_flowers.glb')
